-- WINTER NOTE v4 추가 기능
-- 1) 오늘 할 일: Supabase 동기화
-- 2) 메모 이전 버전 기록

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  todo_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.todos enable row level security;

drop policy if exists "Users can view own todos" on public.todos;
drop policy if exists "Users can create own todos" on public.todos;
drop policy if exists "Users can update own todos" on public.todos;
drop policy if exists "Users can delete own todos" on public.todos;

create policy "Users can view own todos" on public.todos for select using (auth.uid() = user_id);
create policy "Users can create own todos" on public.todos for insert with check (auth.uid() = user_id);
create policy "Users can update own todos" on public.todos for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own todos" on public.todos for delete using (auth.uid() = user_id);

create table if not exists public.note_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id bigint not null references public.notes(id) on delete cascade,
  title text default '',
  content text default '',
  created_at timestamptz not null default now()
);

alter table public.note_versions enable row level security;

drop policy if exists "Users can view own note versions" on public.note_versions;
drop policy if exists "Users can create own note versions" on public.note_versions;
drop policy if exists "Users can delete own note versions" on public.note_versions;

create policy "Users can view own note versions" on public.note_versions for select using (auth.uid() = user_id);
create policy "Users can create own note versions" on public.note_versions for insert with check (auth.uid() = user_id);
create policy "Users can delete own note versions" on public.note_versions for delete using (auth.uid() = user_id);

create index if not exists todos_user_date_idx on public.todos(user_id, todo_date);
create index if not exists note_versions_note_idx on public.note_versions(note_id, created_at desc);
